### PR TITLE
Update the sounds package dependency.

### PR DESCRIPTION
**Pull request by dobey**
Not a big package, but will save use a few more kB in the rootfs.

### CODE REVIEW

**Comment by peat-psuwit** [comment]
Where do the current ringtones come from though?

**Comment by dobey** [comment]
> Where do the current ringtones come from though?

The default call and message sounds come from the `ubuntu-touch-sounds` package,.

**Comment by peat-psuwit** [comment]
Then would it make sense to make this package depends on `ubuntu-touch-sounds` instead? The `ubuntu-sound` package should still be dropped, and we should still get the savings.

**Comment by dobey** [comment]
> Then would it make sense to make this package depends on `ubuntu-touch-sounds` instead? The `ubuntu-sound` package should still be dropped, and we should still get the savings.

Done.

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

**Comment by UniversalSuperBox** [comment]
For QA: Have you noticed any missing ringtones or sounds that previously played? If all ringtones and notification sounds are playing correctly, this change was successful.

**Comment by dadandalive** [comment]
Standard ringtones and sounds all play on N5, RC 2021-W10.

**Comment by ghost** [comment]
Standard ringtones and sounds all play on
BQ Aquaris E4.5 and RC 2021-W10.

**Comment by UniversalSuperBox** [comment]
https://github.com/ubports/ubuntu-touch/issues/1684 is potentially related to this change missing on the android9 branch.

**Pull request merged**
