### PR TITLE
Add support for "Linux standard" pulseaudio profile/port names

### PR DESCRIPTION
**Pull request by mariogrip**

### CODE REVIEW

**Review by UniversalSuperBox — DISMISSED** [review]
This appears to fail several tests and cause a reproducible segmentation fault in others.

**Comment by mariogrip** [comment]
how did a rebase fix the failing test?

**Comment by UniversalSuperBox** [comment]
Likely https://github.com/ubports/telephony-service/commit/33da8746f1b203f0aa8a2e9297cee684e5906b54

**Comment by mariogrip** [comment]
> Likely [33da874](https://github.com/ubports/telephony-service/commit/33da8746f1b203f0aa8a2e9297cee684e5906b54)

ah right! that make sense :D

**Review by UniversalSuperBox — APPROVED** [review]
Tested working on Nexus 5 and OnePlus One.

**Pull request merged**
